# Based on Jan Bracker's supermonad travis file, which is itself based on
# others (https://github.com/jbracker/supermonad/blob/master/.travis.yml)

# Don't use a specific environment. We install everything ourselves.
language: generic

# Don't use sudo so the environment boots faster on travis.
# We can get around sudo, because we are using apt addons to install 
# custom packages.
sudo: false

# Environments we want to build for.
matrix:
  include:
    - env: GHCVER=7.8.4 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}

# Setup tools
before_install:
  - ps uax --forest
install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
  - travis_retry cabal update

# Compilation script
before_script:
  - ghc   --version
  - cabal --version
  - alex  --version
  - happy --version

  # Work in a sandbox
  - cabal sandbox init
  - cd keera-hails-reactivevalues/ && cabal sandbox init --sandbox=../.cabal-sandbox && cd ..
  - cd keera-hails-reactivelenses/ && cabal sandbox init --sandbox=../.cabal-sandbox && cd ..

script:
  # Print version information
  - travis_retry cabal install --reorder-goals --max-backjump=3 --run-tests -j2 keera-hails-reactivevalues/ keera-hails-reactivelenses/

# Deployment
before_deploy:
  - cd keera-hails-reactivevalues/

deploy:
  provider: hackage
  username: keera_studios_ci
  password:
    secure: XouU0aU7U3kFa3HM1ecPdiAR8oscz7VMuTNlSnY7o4ZNIIBg6bEJ2AvZHW0eLIiCerPpox4uyrcxgSw5/L38mXFJYlcHbqVCh+rMxi2DTU73XelUXNQ+tLv0sCHsrWLd97tTpefgzuuNCJ6RoK91Vo8AC84txbgirQLv4WJ8LJWI2danvNUT2q+kTLA9LFxnLC+iNtMi/FxTE56noz6UnbhvzgLUkRgMM/k97CTtM0Q1Iei1vOFzRcjd9D/S3Uzy00cEzARilNe++IE9qTK9aBSXiaNSZtHrT7V3Nou7tIEuU8rE3vBKTSOiZ/fZTqhirufyHC1ORwBRn6DFEDpcTgppL+aFGev6rngoq9d2MIa8qW0E2ijD00BPZhm8KLKODAT2b1SYpIGCUsNyMo98LEzmJPi21SUjoUxUyuX82wtSHPLUgGBAuanHmFIao9jX+Ws04yUhvoWnFaDlwisG6CbFgMI/K8bSn7qdLyrCXFGn/fc5CS2dj9ApCTGS81btIfxSq0s6fax5KmzswsAtxjjdhKn/pkkpIUQPn/qYIAZrN6UGDr57Xw7QobDMibW/CPQ+EAGtAapqHVKaL0ZJxGxXKSthpdhWGPcsDCFIfpnVqEQZTubgzIa7UPagjOKSDy+ErHBxLztCFzZ+wHxUO3OR2kPtVjzqvqcWATLEMOg=
  on:
    branch: master
    condition: "$GHCVER = 8.0.2"

# Notifications
notifications:
  email: true
