# Based on Jan Bracker's supermonad travis file, which is itself based on
# others (https://github.com/jbracker/supermonad/blob/master/.travis.yml)

# # Don't use a specific environment. We install everything ourselves.
# language: generic
# 
# # Don't use sudo so the environment boots faster on travis.
# # We can get around sudo, because we are using apt addons to install 
# # custom packages.
# sudo: false
# 
# # Environments we want to build for.
# matrix:
#   include:
#     - env: GHCVER=7.8.4 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
#       addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
#     - env: GHCVER=7.10.3 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
#       addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
#     - env: GHCVER=8.0.2 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
#       addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}

language: c

env:
#  - GHCVER=7.6.3
#  - GHCVER=7.8.4
#  - GHCVER=7.10.3
 - GHCVER=8.0.1

# env:
#    secure: BAT4/Yvy7AP5HOhMpK0Icq5zc2q3SIU+qaXFSabOMPG1IMYuTvl7x3FQcGGe9izDiAikQhX75LiAU5ABkgxVWdZOl7nHLs4oMqijzkcDxUWQ0TuSsV75wmXL+G5SSdkkPdu5ZQjmrF/Bw+g2Xk+eZzfuo8lareq9ka9/ahfZPKaFxKV98sPutMBihly9uM5CZNQ++7JB/wdLVxacJTHW2Bhx4P7nKz1TwvLBto2gPgCcL372n45nfV46vBTCgB069pan5M5ceuDg7ex8DuVt0hsaKeau0ALD/YXxukVDweRTR3S1DETwExxDh3TShUaQVmnpSrLKh7nztlmDGVMCDCuc8tqUQ/dnsHRQ4nQjajp+lU2BO3GI4NgRRjZAKr5dpxtWOnxvFR4d+qZtGPvkGxnTXCSP2w8MiS7TtIugrsiM7EbGK5Sm5NbCx6bcJ9itonQVAq1y2ZrneIhU7E9h6WLbwd+W/8M+HyN6pExblKtitts+wpnq02A5XGx5gOyl9v2bUwuJq2mxBydrUqrRCvLgFrAqYB+2zJoCQHryDlmzLJr/jG2Nfo2gGjaTZf1yGqe95F1Os+DisdQi3zJa1KkPrco1si74TVPB+SKnawwtTmkrDtoGgBJkxDejHwZ1AXWCpisnQld7Cmxo0xjeZxpvTfYqqKByo5mJGadf/7g=

# matrix:
#   include:
#     - env: GHCVER=7.8.4  CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
#     - env: GHCVER=7.10.3 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
#     - env: GHCVER=8.0.2  CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - unset CC
install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER-prof ghc-$GHCVER-dyn alex-3.1.4 happy-1.19.5
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update


# # Setup tools
# before_install:
#  - unset CC
# install:
#   - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
#   - travis_retry cabal update

# Compilation script
before_script:
  - ghc   --version
  - cabal --version
  - alex  --version
  - happy --version

  # Work in a sandbox
  - cabal sandbox init
  - cabal sandbox add-source keera-hails-i18n
  - cabal sandbox add-source keera-hails-mvc-controller
  - cabal sandbox add-source keera-hails-mvc-environment-gtk
  - cabal sandbox add-source keera-hails-mvc-model-lightmodel
  - cabal sandbox add-source keera-hails-mvc-model-protectedmodel
  - cabal sandbox add-source keera-hails-mvc-solutions-config
  - cabal sandbox add-source keera-hails-mvc-solutions-gtk
  - cabal sandbox add-source keera-hails-mvc-view
  - cabal sandbox add-source keera-hails-mvc-view-gtk
  - cabal sandbox add-source keera-hails-reactive-fs
  - cabal sandbox add-source keera-hails-reactive-gtk
  - cabal sandbox add-source keera-hails-reactive-gtk3
  - cabal sandbox add-source keera-hails-reactivelenses
  - cabal sandbox add-source keera-hails-reactive-network
  - cabal sandbox add-source keera-hails-reactive-polling
  - cabal sandbox add-source keera-hails-reactivevalues
  - cabal sandbox add-source keera-hails-reactive-yampa

script:
  # - travis_retry cabal install --reorder-goals --max-backjump=3 -j2 keera-hails-i18n keera-hails-mvc-controller keera-hails-mvc-environment-gtk keera-hails-mvc-model-lightmodel keera-hails-mvc-model-protectedmodel keera-hails-mvc-solutions-config keera-hails-mvc-solutions-gtk keera-hails-mvc-view keera-hails-mvc-view-gtk keera-hails-reactive-fs keera-hails-reactive-gtk keera-hails-reactivelenses keera-hails-reactive-network keera-hails-reactive-polling keera-hails-reactivevalues keera-hails-reactive-yampa
  - travis_retry cabal install --reorder-goals --max-backjump=3 -j2 keera-hails-reactivelenses keera-hails-reactivevalues

# Notifications
notifications:
  email: true

# deploy:
#   provider: hackage
#   username: keera_studios_ci
#   password:
#     secure: XouU0aU7U3kFa3HM1ecPdiAR8oscz7VMuTNlSnY7o4ZNIIBg6bEJ2AvZHW0eLIiCerPpox4uyrcxgSw5/L38mXFJYlcHbqVCh+rMxi2DTU73XelUXNQ+tLv0sCHsrWLd97tTpefgzuuNCJ6RoK91Vo8AC84txbgirQLv4WJ8LJWI2danvNUT2q+kTLA9LFxnLC+iNtMi/FxTE56noz6UnbhvzgLUkRgMM/k97CTtM0Q1Iei1vOFzRcjd9D/S3Uzy00cEzARilNe++IE9qTK9aBSXiaNSZtHrT7V3Nou7tIEuU8rE3vBKTSOiZ/fZTqhirufyHC1ORwBRn6DFEDpcTgppL+aFGev6rngoq9d2MIa8qW0E2ijD00BPZhm8KLKODAT2b1SYpIGCUsNyMo98LEzmJPi21SUjoUxUyuX82wtSHPLUgGBAuanHmFIao9jX+Ws04yUhvoWnFaDlwisG6CbFgMI/K8bSn7qdLyrCXFGn/fc5CS2dj9ApCTGS81btIfxSq0s6fax5KmzswsAtxjjdhKn/pkkpIUQPn/qYIAZrN6UGDr57Xw7QobDMibW/CPQ+EAGtAapqHVKaL0ZJxGxXKSthpdhWGPcsDCFIfpnVqEQZTubgzIa7UPagjOKSDy+ErHBxLztCFzZ+wHxUO3OR2kPtVjzqvqcWATLEMOg=
#   on:
#     branch: master
#     condition: "$GHCVER = 8.0.2"
deploy:
  provider: script
  # script: cd keera-hails-reactivevalues && cabal check && cabal sdist && cabal upload --username=keera_studios_ci --password=$PASS `find dist/ -iname '*.tar.gz'` || cd .. && cd keera-hails-reactivelenses && cabal check && cabal sdist && cabal upload --username=keera_studios_ci --password=$PASS `find dist/ -iname '*.tar.gz'` || cd .. && true
  script: cd keera-hails-reactivevalues && cabal check && cabal sdist && cabal upload --username=keera_studios_ci --password=$PASS `find dist/ -iname '*.tar.gz'` || cd .. 
          && cd keera-hails-reactivelenses && cabal check && cabal sdist && cabal upload --username=keera_studios_ci --password=$PASS `find dist/ -iname '*.tar.gz'` || cd .. 
          && true
  on:
    branch: develop_travis_upload
    condition: "$GHCVER = 8.0.1"
