# language: haskell
# ghc: 7.8
#      7.6
#      7.4
# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: c
env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - unset CC
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER-prof ghc-$GHCVER-dyn
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH
 - cabal update
 - cabal install happy alex -j1 -v2
install:
 - cd keera-hails-reactivevalues
 - cabal install --enable-tests --disable-library-profiling --disable-executable-profiling --disable-documentation --disable-library-coverage --disable-benchmarks -v2 -j1
 - cabal configure --enable-tests -j1
 - cabal build -v2 -j=1
 - cabal test
notifications:
 email: true
