language: haskell
ghc: 7.8
     7.6
     7.4
env:
  - TEST_DIR=keera-hails-reactivevalues
script:
  - cd $TEST_DIR && cabal configure --enable-tests && cabal build && cabal test
notifications:
    email: true
